# Generated by Django 5.0.2 on 2024-03-01 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact_Form_Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10000)),
                ("phone_number", models.CharField(max_length=10000)),
                ("email", models.CharField(max_length=10000)),
                ("eviction_type", models.CharField(max_length=10000)),
                ("message", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="The_Eviction_Navigators",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "facebook_username",
                    models.CharField(blank=True, max_length=10000, null=True),
                ),
                (
                    "instagram_username",
                    models.CharField(blank=True, max_length=10000, null=True),
                ),
                (
                    "pinterest_username",
                    models.CharField(blank=True, max_length=10000, null=True),
                ),
                (
                    "linkedin_username",
                    models.CharField(blank=True, max_length=10000, null=True),
                ),
                (
                    "x_username",
                    models.CharField(blank=True, max_length=10000, null=True),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("email", models.CharField(blank=True, max_length=10000, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=10000, null=True),
                ),
            ],
        ),
    ]
